# Generated by Django 3.0.4 on 2020-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
