# Generated by Django 3.0.4 on 2020-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
